---
server:
  trackerPort: 6969
  useMagnetometerOnAllTrackers: false
filters:
  type: "prediction"
  amount: 0.2
driftCompensation:
  enabled: false
  prediction: false
  amount: 0.8
  maxResets: 6
oscRouter:
  enabled: false
  portIn: 9002
  portOut: 9000
  address: "127.0.0.1"
vrcOSC:
  enabled: false
  portIn: 9001
  portOut: 9000
  address: "127.0.0.1"
  trackers:
    right_foot: true
    left_foot: true
    waist: true
  oscqueryEnabled: true
vmc:
  enabled: false
  portIn: 39540
  portOut: 39539
  address: "127.0.0.1"
  anchorHip: true
  vrmJson: null
  mirrorTracking: false
autoBone:
  cursorIncrement: 2
  minDataDistance: 1
  maxDataDistance: 1
  numEpochs: 50
  printEveryNumEpochs: 25
  initialAdjustRate: 10.0
  adjustRateDecay: 1.0
  slideErrorFactor: 1.0
  offsetSlideErrorFactor: 0.0
  footHeightOffsetErrorFactor: 0.0
  bodyProportionErrorFactor: 0.05
  heightErrorFactor: 0.0
  positionErrorFactor: 0.0
  positionOffsetErrorFactor: 0.0
  calcInitError: false
  randomizeFrameOrder: true
  scaleEachStep: true
  sampleCount: 1500
  sampleRateMs: 20
  saveRecordings: false
  useSkeletonHeight: false
  randSeed: 4
  useFrameFiltering: false
  maxFinalError: 0.03
keybindings:
  fullResetBinding: "CTRL+ALT+SHIFT+Y"
  yawResetBinding: "CTRL+ALT+SHIFT+U"
  mountingResetBinding: "CTRL+ALT+SHIFT+I"
  pauseTrackingBinding: "CTRL+ALT+SHIFT+O"
  fullResetDelay: 0
  yawResetDelay: 0
  mountingResetDelay: 0
  pauseTrackingDelay: 0
skeleton:
  toggles: {}
  values: {}
  offsets: {}
  hmdHeight: 0.0
  floorHeight: 0.0
legTweaks:
  correctionStrength: 0.3
  alwaysUseFloorclip: false
tapDetection:
  yawResetDelay: 0.2
  fullResetDelay: 1.0
  mountingResetDelay: 1.0
  yawResetEnabled: true
  fullResetEnabled: true
  mountingResetEnabled: true
  setupMode: false
  yawResetTaps: 2
  fullResetTaps: 3
  mountingResetTaps: 3
  numberTrackersOverThreshold: 1
resetsConfig:
  resetMountingFeet: false
  mode: "BACK"
  yawResetSmoothTime: 0.0
  saveMountingReset: false
  resetHmdPitch: false
trackers: {}
bridges:
  steamvr:
    trackers:
      right_knee: false
      chest: false
      right_foot: false
      right_hand: false
      left_foot: false
      left_hand: false
      waist: false
      right_elbow: false
      left_knee: false
      hmd: false
      left_elbow: false
    automaticSharedTrackersToggling: true
  steamvr_feeder:
    trackers: {}
    automaticSharedTrackersToggling: true
knownDevices: []
overlay:
  mirrored: false
  visible: false
modelVersion: "14"
