# .github/workflows/docker-publish.yml
# Workflow to build and publish Docker images to Docker Hub

name: "Build and Publish Docker Images"

on:
  push:
    branches:
      - main          # runs on push to main branch
    tags:
      - 'v*'          # runs on push of semantic version tags (e.g., v1.2.3)

env:
  SLIMEVR_VERSION: ${{ env.SLIMEVR_VERSION != '' && env.SLIMEVR_VERSION || secrets.SLIMEVR_VERSION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      # 3. Initialize Docker Buildx for enhanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Authenticate with Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # set in repository Settings > Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Docker Hub access token

      # 5. Build and push the SlimeVR server image
      - name: Build and push SlimeVR server image
        uses: docker/build-push-action@v3
        with:
          context: ./slimevr                       # path to SlimeVR Dockerfile
          platforms: linux/amd64,linux/arm64      # target architectures
          push: true                              # push image after successful build
          tags: |
            madkoding/slimevr-server:latest
            madkoding/slimevr-server:${{ github.sha }}

      # 6. Build and push the WebGUI Nginx image
      - name: Build and push WebGUI image
        uses: docker/build-push-action@v3
        with:
          context: ./nginx                        # path to Nginx Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            madkoding/slimevr-web-server:latest
            madkoding/slimevr-web-server:${{ github.sha }}
